### ISSUE TITLE
404 on nginx server

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#183]
When we host Bedrock prototypes on an nginx server, this is the 404.

How do we show the actual 404 page?

<img width="878" alt="screen shot 2017-12-14 at 15 17 18" src="https://user-images.githubusercontent.com/12690/33996581-efcdb220-e0e1-11e7-9ead-ffa37ea0e719.png">

**Comment by xavez** [comment]
I think this is an issue related to the server settings, and not so much Bedrock?

**Comment by Wolfr** [comment]
It might be, but still something we should investigate.

**Comment by Wolfr** [comment]
The server should probably direct tot 404.html when content is hosted statically.

Xavier was right ;) I just didn't know how it worked at the time.
