### ISSUE TITLE
Bedrock 2.0

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#191]
After 2+ years of Bedrock I think is is time to start thinking about Bedrock 2.0.

Here are some of my main ideas. Any suggestions are welcome.

**Javascript loading**

I need some help in figuring out what to modernize, because I am out of touch with some of the recent evolutions in the Javascript world.

**Make it easy to integrate Bedrock results into React/Angular 5**

Can we somehow make it easier to integrate into modern stacks using React or Angular 5?

Can we build a similar compiler/logic where styles are confined to the objects themselves or is this really crazy/too much work?

**Template language change**

I know what I want, which is essentially the same functionality as Bedrock 1.0, but it should be more approachable to a broader group of people. So one idea that I had is **getting rid of Pug/Jade**.

Even though I have grown to love it, there is something to be said about easily being able to copy paste HTML/CSS to an implementation. I have little experience with it but what I've seen from [Nunjucks](https://mozilla.github.io/nunjucks/) is quite cool

---

I think when we know what we want, we can start planning its development. It maybe doesn't have to be now, but I would like to keep evolving this project over time.

Your input is welcome!

**Comment by xavez** [comment]
- What exactly do you mean with "JavaScript loading"?
- Integrating Bedrock results with React / Angular 5; this depends on what you mean. Copy pasteability of Pug templates into Vue, for instance, is already a great plus. I think if we move more towards the dev end of the spectrum, we’ll end up having a React or Angular app, in stead of a static site generator. This also doesn’t rhyme with the goal of broader adaptation for me.
- Regarding template language, I think I would be sad to see Pug go because it is so powerful and so simple at the same time. The ability to use JavaScript in template logic is pretty damned cool.

**Comment by Wolfr** [comment]
> What exactly do you mean with "JavaScript loading"?

I have the feeling our methods (RequireJS?) are a bit out of date. Not sure though as like I said I am a bit out of touch with modern JS methods to include libraries/files. Related issue #184 .

**Comment by Wolfr** [comment]
>  The ability to use JavaScript in template logic is pretty damned cool.

This is also a feature of Nunjucks btw.

**Comment by xavez** [comment]
- We use [Browserify](http://browserify.org) to include JS modules, I’m sure @thomastuts knows more about how modern this is. Most projects I know of seem to be going the [Webpack](https://webpack.js.org) way for assets, of course this is broader than just JS modules.
- Concerning Nunjucks: I couldn’t find that in the documentation. But other than that it seems like a very powerful templating language. Perhaps it is similar to our choice of preferring SCSS over Sass syntax or Stylus: a valid HTML document is a valid Nunjucks document, and that is pretty powerful in itself – especially for newcomers. The question is then reduced to this: is the thing we are building targeted at newcomers, or is a steeper learning curve interesting? And also: how hard would it be to swap templating languages by way of personal preference?

**Comment by Wolfr** [comment]
What I found when I was building a styleguide for the Mono website (which is mostly PHP and HTML) it was super annoying to convert to `.pug`.

So I made an experimental repo where I changed the template language over to Nunjucks. It is completely broken at the moment but swapping it out doesn't seem as much work as I anticipated.

What I am thinking is that if I have to explain Bedrock to someone with just base HTML/CSS experience, at least they don't have to jump over the gap to learn Pug.

I really believe a templating language that is closer to HTML will increase possible adoption.

It also allows you to easily copy/paste things from other libraries to start creating Bedrock docs e.g. you could just go to material.io and start copy/pasting 1 by 1 to build your library of UI elements.

I also researched the usage of inline Javascript in Nunjucks, and while I said it's possible to use inline JS in Nunjucks, it turns out to not really be the case.

Nunjucks explicitly doesn't do this to confine itself to templating. But what use case are you thinking about where you need to do inline JS? You can set variables, work with JSON data etc. in Nunjucks no problem. You can't do something like `Date.now()` but there are ways around it.

**Comment by Wolfr** [comment]
In the end, the solution was to use the frameworks built around the tech stacks and implement Bedrock's functionality in them (and not the other way around), as per this [spec](https://gist.github.com/Wolfr/38a6495eba18a2327d0d012dcc9a974b).
