### ISSUE TITLE
Config object

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#194]
Can we somehow document the config object inline with comments?

It is a Javascript object, can we split it in multiple sections somehow while retaining the fact that it's an object?

I want to have some commented sections.

E.g. add comments like 

```
# Styleguide generation: existence of this section determines whether the styleguide gets generated or not

styleguide.colors # Location of your colors SCSS file
```

Technical advice wanted :)

Ref: https://github.com/mono-company/bedrock/blob/master/bedrock.config.js

**Comment by Wolfr** [comment]
I think Thomas is on a holiday but let's check with a JS expert later :)

**Comment by tdurand** [comment]
Yes you definitely can comment inline the JS config object, it's allowed, you can either comment with multiline comment or inline comments. _For your information you can't have comments in JSON object, but JS objects are fine_

Here is an example

```javascript
module.exports = {
  /**
   *  Styleguide generation: existence of this section 
   *  determines whether the styleguide gets generated 
  */
  styleguide: {
    snippetLanguage: 'html',
    colors: './content/scss/_settings.colors.scss', // Location of your colors SCSS file
    categoryOrder: [
      'Style guide',
      'Patterns',
      'Overviews',
      'Components',
    ],
    componentCategories: {
      b: 'Bootstrap additions',
      f: 'Foundation additions',
      bc: 'Bootstrap custom components',
      fc: 'Foundation custom components',
      br: 'Bedrock components',
      c: 'Custom components'
    }
  }
```

**Comment by Wolfr** [comment]
That is clear 👍
You can tell we don't write a lot of modern JS ;)
