### ISSUE TITLE
1.10 Material dialog

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#223]
https://cl.ly/3l2H072m2k2d

The material dialog docs don't actually show dialogs.

**Comment by Wolfr** [comment]
Typically when we do modal docs, we write some specific code in styleguide.scss to show them static (if for example the code uses fixed positioning)

<img width="1440" alt="screen shot 2018-06-13 at 14 19 03" src="https://user-images.githubusercontent.com/12690/41350849-bff0718e-6f14-11e8-9d9f-059352c1776e.png">

**Comment by bosschaertB** [comment]
#230
