### ISSUE TITLE
1.10 Material - Better typography for docs

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#231]
<img width="1104" alt="screen shot 2018-06-15 at 09 58 47" src="https://user-images.githubusercontent.com/12690/41457065-bf09a136-7082-11e8-89f5-08c36e8f4d10.png">

The top paragraph should have better styles. We can fix this by adding a class to the `p` - namely `p.mdc-typography--body1` but since we can't apply classes in the documentation (since the `_docs.md` is a markdown file, we can't style this this way.

**Comment by Wolfr** [comment]
Idea, do something like: 

````
.br-content {
  p {
    @include mdc-typography(body1);
  }
}
````

**Comment by Wolfr** [comment]
Can you look into this @bosschaertB ?

**Comment by bosschaertB** [comment]
@Wolfr I'll check, when data-table is fixed

**Comment by Wolfr** [comment]
Looks pretty terrible at the moment

https://cl.ly/1l361P3s3Z0u

I added some classes by writing html in markdown, but this solution doesn't really scale.

I checked in Google's own documentation and they just wrote their own typography styles I guess we have to do something similar to make it look good.

**Comment by bosschaertB** [comment]
Like this e9f6029b25f03d7c371eba5c29de5e03ee5f4955?

**Comment by Wolfr** [comment]
It helps, I fixed it up some more.
