### ISSUE TITLE
1.10 Material - Select examples

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#244]
Select examples are too specific and JS seems broken.

* [x] Make more generic
* [x] Make the animation/floating label things work
* [x] Fix the notch thing

**Comment by Wolfr** [comment]
By "too specific" I mean that the examples with "Food group" etc. would need to be rewritten by authors when prototyping, it's better to put something super generic in there.

https://cl.ly/3b2A003k3J3H

**Comment by bosschaertB** [comment]
All working, except the outlined select box

**Comment by Wolfr** [comment]
...and that is the one we need unfortunately http://materialbase.bedrockapp.org/examples/form.html

**Comment by bosschaertB** [comment]
Damn, ok I'll search for a solution

**Comment by Wolfr** [comment]
Closing this because the last remaining issue was also in #254
