### ISSUE TITLE
1.10 Material Design - Spinner

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#245]
Do we have some kind of spinner component in the official components?

https://cl.ly/2z0D400U2Q2k

**Comment by Wolfr** [comment]
We can add this as an "unofficial"

e.g https://codepen.io/gaffareljeremie/pen/owjhF

**Comment by bosschaertB** [comment]
Alright!

**Comment by bosschaertB** [comment]
@Wolfr They have a progress indicator, but they only have the linear one. Guess it's still under development https://material.io/develop/web/components/linear-progress/

**Comment by bosschaertB** [comment]
https://github.com/usebedrock/bedrock/commit/d71c792dba874dae0af6da65a1ec60741349389a

**Comment by Wolfr** [comment]
Looks good, I improved the code a bit.

Note that in Bedrock we don't need vendor prefixes because these get added by our gulp task.
