### ISSUE TITLE
1.10 Material - Heading margins

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#246]
Because we use a reset some of the margin spacings have disappeared

we need to add them manually since Material does not cover this

https://cl.ly/252j2i433G3U

**Comment by Wolfr** [comment]
@bosschaertB you could give this a go but otherwise I will do it

**Comment by bosschaertB** [comment]
Ok, this is in the core code?

**Comment by Wolfr** [comment]
Hmm... I think maybe there are 2 types of classes on the headings:

`.mdc-typography-xxx` where that sets the font family

Those are controlled via the styleguide settings block (see master template) 

But then we also have things like

`.br-componentgroup-header` which we can use to set the spacing, specifically for the styleguide

I would put this code in `styleguide.scss`

So for example

````
.br-componentgroup-header {
   margin: 0 0 20px;
}
````

In a regular project we would probably add some spacing utility classes.

The thing is I don't want to add utility classes for spacing since then the codebase diverges too far from Google's `material-components-web`.

**Comment by Wolfr** [comment]
I did this and then ported some of that code over to the `develop` branch.
