### ISSUE TITLE
1.10 Material - Data table checkbox highlight margin scaling

### ISSUE THREAD

**Issue by bosschaertB** [usebedrock/bedrock#253]
The ripple effect add additional scaling properties to the .mdc-checkbox highlight circle. Need to test were the styling is coming from and how to fix this issue

**Comment by Wolfr** [comment]
It might be `content-box` / `border-box` related stuff coming from Bedrock where Bedrock sets `box-sizing: border-box` but Google's material design expects `content-box`.

**Comment by bosschaertB** [comment]
Fix 5e116d378f72e1b638b2ca40df53a8686d365feb
