### ISSUE TITLE
1.10 Material icon button

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#255]
Do we have this documented?
https://material-components.github.io/material-components-web-catalog/#/component/icon-button

**Comment by Wolfr** [comment]
I think we don't have it, we do have a button with an icon and text part of the buttons, but this doesn't exist yet. Perhaps we can just add it to the button docs, a separate page seems a bit overkill.

**Comment by bosschaertB** [comment]
Still need to fix the ripple effect. It's added in the content JS, but it messes up the css of the icon button 0188d34c4f6400b814b0810e4ae90cc0e5fb791b

**Comment by bosschaertB** [comment]
Really been searching for an hour, nothing I try seems to work properly.

**Comment by bosschaertB** [comment]
Fix 024bb64149b8d3059c9d8263b7651c1ccc78abb0
