### ISSUE TITLE
1.10 Material - Document mdc-layout grid

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#256]
Document how to use `mdc-layout-grid` with examples.

**Comment by Wolfr** [comment]
In other projects we have highlighted the columns with a bit of custom code for demo purposes, like so:

````
/* Expose columns in grid documentation
   ========================================================================== */

.br-styleguide #component-01-o-grid [class*=o-grid-col] {
  color: #FFF;
  background: #4FB8D4;
  margin-bottom: 1.6rem;
  padding: 1rem;
  text-align: center;
}````

**Comment by Wolfr** [comment]
I made it but perhaps we can improve it a bit in terms of looks

use the theme color?

**Comment by bosschaertB** [comment]
Added theme color d56d2354c7bd753cc05d6406c9ef957d1d1299f4
