### ISSUE TITLE
1.10 Material document elevation

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#258]
Document elevation

**Comment by Wolfr** [comment]
Like it is documented here? https://material.preactjs.com/component/elevation

**Comment by Wolfr** [comment]
Not so sure if we need this, definitely not a priority.

**Comment by Wolfr** [comment]
Investigate to use code like this:

````
div {
   @include mdc-elevation(2);
}
````

**Comment by bosschaertB** [comment]
Added elevation demo f9b8ba4d25b3fcdc3159ec98d011fef1e3b04d31
