### ISSUE TITLE
1.10 Material - Improve styling of color documentation in material design base

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#269]
Looks a bit wonky 
https://cl.ly/2s3j302Z3U1w

**Comment by bosschaertB** [comment]
<img width="265" alt="screen shot 2018-06-21 at 16 26 51" src="https://user-images.githubusercontent.com/9121648/41725404-f1bb1d66-756f-11e8-9f10-c0b1af56cb97.png">

Their own example is messed up, I guess we'll have to tweak this one ourselves.
