### ISSUE TITLE
1.10 Build fails on SVG icon rendering

### ISSUE THREAD

**Issue by brenner-company** [usebedrock/bedrock#272]
**OS:** Windows 8.1
**Node:** v8.4.0

Gulp build fails at rendering of SVG icon. Error output (with fresh clone of Bedrock):
```shell
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: core\templates\mixins\sample.pug:11
    9|         if component.docs
    10|             .br-sample-documentation(class=styleguideRichContentClass)!= component.docs.body
  > 11|         .br-sample-content!= render(component.filename, 'html')
    12|         .br-sample-footer
    13|             if config.styleguide.snippetLanguage === 'html'
    14|                 button.br-sample-show-code-btn(class=styleguideButtonClass) Show HTML code

core\templates\mixins\icon.pug:7
    5|         div(class=`${svgIconClassPrefix} ${svgIconClassPrefix}-${name.replace('/', '-')} ${extraClasses}`)!= renderSvgIcon(name)
    6|     else
  > 7|         div(class=`${svgIconClassPrefix} ${svgIconClassPrefix}-${name.replace('/', '-')}`)!= renderSvgIcon(name)
    8|

ENOENT: no such file or directory, open 'D:\Repositiories\Various\Bedrock\content\icons\contenticons\16\check.svg'
```

Seems like, looking at the erroneous path containing `\contenticons\`, paths are formed differently on Windows devices: `\` instead of `/` as directory separators.

The following line of JS (within icons.js - line 18) will try to remove a part of that path but will fail at it:
```js
let category = parsedPath.dir.replace(`${paths.content.icons.sourceDirectory}`, '').replace('/', '');
```

Adjusting this line to include an extra string replacement seems to fix this:
```js
let category = parsedPath.dir.replace(paths.content.icons.sourceDirectory.replace(/\\/g, '/'), '').replace('/', '');
```

**Comment by Wolfr** [comment]
Hmm yes, this reminds me of very old issue https://github.com/usebedrock/bedrock/issues/110 .

It has been a while since we tested Bedrock on Windows,

I will check this code and verify the fix, thanks so much for investigating.

**Comment by brenner-company** [comment]
I searched for similar issues first but must have looked over it. Seems similar indeed.

No problem, glad to help!

**Comment by Wolfr** [comment]
I've put this change in, I have no Windows machine nearby to test but it seems to still work on Mac after editing the code, so I assume it is alright.

Thank you!
