### ISSUE TITLE
1.10 Build fails on icon (only svg) overview generator

### ISSUE THREAD

**Issue by brenner-company** [usebedrock/bedrock#273]
**OS:** Windows 8.1
**Node:** v8.4.0

Gulp build fails at icon overview generation, but only with svg's. Error output (with fresh clone of Bedrock):
```shell
TypeError in plugin 'gulp-pug'
Message:
    D:\Repositiories\Various\Bedrock\core\templates\mixins\icon-overview.pug:5
    3|         each icon in icons.svg[category]
    4|             div
  > 5|                 +icon([category, icon.name].join('/'))
    6|                 code= icon.name
    7|
    8|     - var iconFontClassPrefix = config.icons && config.icons.iconFontClassPrefix || 'if';

pug_mixins.icon is not a function
Details:
    path: D:\Repositiories\Various\Bedrock\core\templates\mixins\icon-overview.pug
```

Added the following line of pug code (within icon-overview.pug - line 1) seems to fix the issue:
```pug
include icon
```

I have no real idea why this does fix the issue (don't know pug that well), but maybe it's a starting point.

**Comment by Wolfr** [comment]
`+icon` refers to a mixin called `icon`

`include icon` is including a file called `icon.pug`

in `icon.pug`, the mixin is defined.

But actually this mixin logic has been recently rewritten,  it's better to document SVG icons like this:

````
each category, id in icons.svg
    if id
        h3 #{id}
    each icon in category
        .svg-icon
            +icon(icon.category+'/'+icon.name)
            p #{icon.name}
````

We used to have 2 types of icon overviews and we had some logic going on with a mixin called icon-overview, but this is no longer necessary.

See https://github.com/usebedrock/bedrock/commit/0f834d3c1cacd6bc22563d150ef6a1804f5c1c52 this will land in a next release soon.
