### ISSUE TITLE
Some notes on setup

### ISSUE THREAD

**Issue by xavez** [usebedrock/bedrock#277]
A while ago, I made some notes on setting up Bedrock on a pristine machine. These are the steps I identified you need to take in order to make sure you have a good , versioned dev environment where Bedrock works reliably on macOS. Some of these things will not be very apparent to newcomers:

## General installation

- [Install homebrew](https://brew.sh)
- `brew install nvm`
- `nvm install 8.3`
- Clone Bedrock via GitHub
- Open the project directory in terminal 
- `npm install`
- `gulp`

## Specfic to icon fonts

- Install xcode command line tools
- `xcode-select --install`
-  [Install RVM](https://rvm.io/rvm/install)
- Install ruby 2.3.0 via `rvm`
- `brew install fontforge`
- `gem install bundler`
- run `bundle install` In the project root

I think it would be helpful if we could document this someplace for newcomers, but I’m not sure if everyone agrees with that, so I wanted to ask about it here first.

**Comment by Wolfr** [comment]
I think we can add some more specifics to the website on this page:
https://bedrockapp.org/documentation/requirements/

But I think we have to be careful about what we communicate and where.

You are correct that this is a technically better way to set up your system but it also contains things that a user might never need.

Maybe most newcomers will never use icon fonts.

Nvm and rvm are technically better ways to install dependencies but they also add a layer of complexity that a beginner might not need.

The easiest way to set up Bedrock from a pristine machine is to install a recent version of Node, install gulp globally and then just start using Bedrock. 

In fact I don't use nvm and rvm at all myself... I got Bedrock running on Mac OS Mojave with just the commands mentioned  in the basic tutorial: https://bedrockapp.org/documentation/basic-tutorial/ .

Related to icon font docs I do think there is a problem with the instructions right now where some info is on Bedrocks README ( https://github.com/usebedrock/bedrock ) and some is on the website.

So I propose we change the README to point to the requirements, and update the requirements with 2 sections: 1. Basic requirements 2. Advanced setup (Mac only) where (2) documents your method of setting up things (Mac only)

What do you think?

**Comment by Wolfr** [comment]
As a first step, I added your guide to this page --> https://bedrockapp.org/documentation/requirements/

**Comment by xavez** [comment]
@Wolfr that’s great, I think we can close this issue and improve later if needed :-)
