### ISSUE TITLE
Upgrade to Gulp 4 needed

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#308]
We've been postponing doing an upgrade to Bedrock for some time.

There is a problem with the `natives` package, which is used by `gulp`, which we use version 3.9.1 of. 

Natives is entirely deprecated. https://www.npmjs.com/package/natives .

Gulp 4 does not rely on natives anymore. It seems like we need to upgrade to version 4 of gulp for Bedrock 1 to avoid future problems.

**Comment by xavez** [comment]
Some background info: https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/
