### ISSUE TITLE
Rewrite content JS to use ES2015 imports

### ISSUE THREAD

**Issue by thomastuts** [usebedrock/bedrock#317]

**Comment by Wolfr** [comment]
The `index.js` file in core uses ES2015 imports but the `index.js` in `content` doesn't yet.

`require('../../core/js/index');`

If I am not mistaken.

**Comment by Wolfr** [comment]
Can you take a look @thomastuts ?

**Comment by Wolfr** [comment]
There's still an old style require around;
`const rememberScroll = require('./styleguide-remember-scroll');`

**Comment by Wolfr** [comment]
@thomastuts is it wrong to still use `require`?

Referring to this line of code https://github.com/usebedrock/bedrock/blob/master/core/js/index.js#L10

**Comment by thomastuts** [comment]
Fixed in https://github.com/usebedrock/bedrock/commit/6e90a895bcf011dc7c5305e2afab64606ec004fd
