### ISSUE TITLE
Looking for advice re: environments & configuration for dev vs production builds

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#383]
I've been building out some features like CSS and JS minification. Currently these are settings in the `bedrock.config.js` file:

```
module.exports = {
  js: {
    minify: false
  },
  css: {
    compiler: 'scss',
    minify: false,
    purge: false
  },
```

Currently if you build a Bedrock static site you have to apply some steps to take it to production such as removing the wrappers (#380 ). And you would also have to change some of these settings above.

I want to eliminate these steps programatically by being able to set a `production` flag somewhere and to be able to easily switch between dev and production.

What's the way to go?

* I don't know much about environment variables, is this the way to go? Should we set an environment variable somehow?
* A separate command that builds for production seems the simplest? `npm run build --production` 

This would then read out a config file. How to organize this?

* Apply a config on top of another config with overrides on top of the default Bedrock config? I.e. set `js.minify` to `true` in this one. Is it even advisable to try and merge JS objects?
* Split up bedrock.config.js in `bedrock.config.dev.js` and `bedrock.config.production.js` and use the right config based on command used?

Input wanted!

**Comment by jedi4ever** [comment]
I see people mixing configs, environments and builds all the time ;
I know it's "common" practice to inject config at build time , but I believe it's an anti-pattern

Here's my take

- CI should make a --production build and archive that artifact somewhere
- A build should be the same across all environments - versioned , recorded how it was build etc..
- Then that 1 artefact should be used across all other environments
- So deploys become checkout the artefact that was test and deploy that one (not rebuild one with a config)

- A developer build is special in that this one is used during development

As for configs:
- the builds needs to find the correct config somehow
- if all config is public you might include all of them - and check f.i. the url to match the right config
- or you might have the build read it from a known place 'config.js' - that get's deployed as part of deploy to the specific environment

**Comment by simonwuyts** [comment]
You can use the `NODE_ENV` environment variable for this. You can alter your npm script like this to set it to 'production':

```
NODE_ENV=production npm run build
```

If for example you only want to enable minification when NODE_ENV is set to 'production', you can alter `config.js` like this:

```js
module.exports = {
  js: {
    minify: process.env.NODE_ENV === 'production'
  }
}
```

As soon as development and production configs become too different, I would switch to using two separate config files and import the right one based on this environment variable.

**Comment by meduzen** [comment]
## 1) Commands

I’d go for a separate command (`npm run production`).

You can check examples in [Can We sources](https://github.com/meduzen/canwe):

- The [`num run production`](https://github.com/meduzen/canwe/blob/master/package.json#L11) command is passing a `node-env` variable to the builder (Webpack, but also works in Gulp I think): 

```json
"production": "node_modules/webpack/bin/webpack.js --node-env=production --config=webpack.config.js"
```

- The `node-env` variable (with a hyphen) becomes `process.env.NODE_ENV` (with an underscore) in the build script, and is used to set a [`isProd` flag](https://github.com/meduzen/canwe/blob/master/webpack.config.js#L3) to toggle further operations like [CSS minification](https://github.com/meduzen/canwe/blob/master/postcss.config.js#L25) or [which kind of sourcemap](https://github.com/meduzen/canwe/blob/master/webpack.config.js#L103) you want to ship:

```js
const isProd = process.env.NODE_ENV === 'production'
```

## 2) Config file

I’d say: have your config file with defaults, and merge the user one in yours.

Alternatively, if your config file can be summarized to a set of `"key": "value"`, I’d consider going for a [.env](https://github.com/meduzen/canwe/blob/master/.env.example) file (that is [added to the .gitignore](https://github.com/meduzen/canwe/blob/master/.gitignore#L5), but you still provide the default in a [`.env.example`](https://github.com/meduzen/canwe/blob/master/.env.example) that is not in the .gitignore):

```sh
APP_ENV=local
AM_I_COOL=true # answer honestly
```

Then you need the [`dotenv` package](https://github.com/meduzen/canwe/blob/master/webpack.config.js#L2) to access the content of this `.env` file ([examples](https://github.com/meduzen/canwe/blob/master/webpack.config.js#L135-L139)):

```js
const env = require('dotenv').config().parsed

if (env.AM_I_COOL) {
  // do something cool
}
```

**Comment by Wolfr** [comment]
Thanks everyone :) thanks to some bits and pieces from all your answers I got to my first implementation.

In the end I went for 3 configs (default config, user config (for dev) and user production config). They inherit values from each other.

There is a simple `npm` command `npm run build-prod` to generate a production build.

Coming up in Bedrock 1.37 👀
