### ISSUE TITLE
Beautify HTML output

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#86]
http://cl.ly/093n2X3w440V/Screen%20Shot%202016-01-25%20at%2015.34.02.png

If I check the HTML output, we have something like this:
https://gist.github.com/Wolfr/b23a1cb8c367667fd305

I'd want something like this:
https://gist.github.com/Wolfr/b23a1cb8c367667fd305

In the past I solved this by beautifying the output.

**Comment by Wolfr** [comment]
Past solution involved "unformatted" option using https://www.npmjs.com/package/grunt-prettify .

**Comment by Wolfr** [comment]
I saw this recently, this is still a relevant issue as well.

**Comment by svenpeeters** [comment]
In a recent project I really liked [js-beautify](https://github.com/beautify-web/js-beautify). 
It is possible to use the `.editorconfig` as common thread.

**Comment by Wolfr** [comment]
This was implemented in https://github.com/usebedrock/bedrock/pull/286 .
